# Generated by Django 3.2.5 on 2022-01-27 14:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220125_0742'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='contact',
        #     old_name='listing',
        #     new_name='bar',
        # ),
        # migrations.RenameField(
        #     model_name='contact',
        #     old_name='listing_id',
        #     new_name='bar_id',
        # ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='user_id',
            new_name='contact_id',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('recipient1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='store.customer')),
                ('recipient2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
            ],
            options={
                'ordering': ['is_read', '-created'],
            },
        ),
    ]
