# Generated by Django 3.2.5 on 2021-07-31 21:43

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0002_bar'),
        ('store', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bar',
            field=models.ForeignKey(blank=True, default=None, on_delete=models.SET(store.models.get_deleted_bar), to='bars.bar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
