# Generated by Django 3.2.5 on 2021-12-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
