# Generated by Django 3.2.5 on 2022-01-11 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_tip', models.TextField(blank=True, null=True)),
                ('key_ingredients', models.CharField(blank=True, max_length=200, null=True)),
                ('key_benefits', models.CharField(blank=True, max_length=200, null=True)),
                ('suitable_for', models.CharField(blank=True, max_length=200, null=True)),
                ('for_best_results', models.CharField(blank=True, max_length=200, null=True)),
                ('made_with', models.CharField(blank=True, max_length=200, null=True)),
                ('smells_like', models.CharField(blank=True, max_length=200, null=True)),
                ('notes_of', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
