# Generated by Django 3.2.5 on 2021-09-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0002_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bars',
            name='photo_main',
            field=models.ImageField(default='/placeholder.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
