# Generated by Django 3.2.5 on 2022-01-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0004_alter_bar_photo_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
