# Generated by Django 3.2.5 on 2022-01-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0005_bar_for_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='clays',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
