# Generated by Django 3.2.5 on 2021-07-29 20:47

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
