# Generated by Django 3.2.5 on 2021-07-29 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-added']},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='videoURL',
        ),
        migrations.AddField(
            model_name='video',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
