# Generated by Django 3.2.5 on 2021-10-15 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_expenses_purchase_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='quantity',
            new_name='quantity_available',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='distributer',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='purchaser',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='expenses',
            name='distributer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='expenses',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='expenses',
            name='model_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='expenses',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenses',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='expenses',
            name='unit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='expenses',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.expenses'),
        ),
    ]
